### ISSUE TITLE
Cleanup on archive name and metadata

### ISSUE THREAD

**Issue by bhmiel-cdphe** [jevans-cdphe/oip-ecmc#4]
The archive here is named oip-ecmc for our repository of handling data/code from ECMC's databases.  

Recommend we rename the code package here to more accurately reflect what it does: export ECMC's annual production for each well/borehole 

Also, need to somewhere create a data dictionary of the fields the output csv for more advice to users.  For fields that come from ECMC's databases we can use their version of a data dictionary, but we need to create one for our own fields.  We should also indicate which fields come from us and from the raw databases.

**Comment by jevans-cdphe** [comment]
Internal CDPHE issues are now being tracked in Azure DevOps. GitHub issues are for public submissions going forward.
