### ISSUE TITLE
NaN value in CSV export

### ISSUE THREAD

**Issue by bhmiel-cdphe** [jevans-cdphe/oip-ecmc#7]
Today was ingesting the data from this project into ArcGIS pro to map the results, only to realize that ArcPro does not recognize "NaN" in a CSV as a null value.  Thus the BOEd column is auto-detected as text rather than float when perfoming the "add XY data" to ingest the data into a *.gdb

Fixed manually as a one off issue now, but going forward better practice is to ensure the csv export outputs blank values rather than "NaN" to prevent this from happening in the future.

**Comment by jevans-cdphe** [comment]
Internal CDPHE issues are now being tracked in Azure DevOps. GitHub issues are for public submissions going forward.
